name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-html

      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Run Playwright tests
        run: pytest -s -v --html=report.html --video=retain-on-failure

      - name: Test natijalarini yuklash (Artefaktlar)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            report.html
            **/*.webm
          retention-days: 30  # Artefaktlar 30 kun saqlanadi
