name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright python-dotenv
    - name: Install Playwright browsers
      run: playwright install --with-deps
    - name: Create .env file
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
    - name: Ensure test results directory exists
      run: mkdir -p test-results
    - name: Run your tests
      run: pytest Tests/Test_internet_heroukapp.py -s -v --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
